export const SET_LIST_LEAGUE = 'SET_LIST_LEAGUE';
export const SET_LIST_TEAM = 'SET_LIST_TEAM';
export const SET_CALENDAR_LEAGUE = 'SET_CALENDAR_LEAGUE';
export const SET_CATEGORY_LEAGUE = 'SET_CATEGORY_LEAGUE';
export const SET_DATE_FROM_LEAGUE = 'SET_DATE_FROM_LEAGUE';
export const SET_DATE_TO_LEAGUE = 'SET_DATE_TO_LEAGUE';
